openapi: "3.0.3"
info:
  title: Web3admin
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /users/signUp:
    post:
      tags:
        - Security
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#components/schemas/UserSignUpPayload"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#components/schemas/User"
  /users/signIn:
    post:
      tags:
        - Security
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#components/schemas/UserSignInPayload"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: Bearer
                  user:
                    $ref: "#components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        profil_picture_id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
    UserSignInPayload:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    UserSignUpPayload:
      allOf:
        - $ref: "#components/schemas/UserSignInPayload"
        - type: object
          properties:
            username:
              type: string
